### PR TITLE
Create non-custodial.md

### PR DESCRIPTION
**Pull request by ManyRios**
list of non-custodial exchanges(dex) where users can buy zcash
related to: https://github.com/ZecHub/zechub/issues/462

t1RHzKQB3L7Q1tHtTLSRLFo12bqBeTb6agi

### CODE REVIEW

**Comment by ManyRios** [comment]
> Check out: https://zlink.click/

Added

**Comment by ManyRios** [comment]
Any update about this @JJ-Rogers @dismad ?

**Review by JJ-Rogers — CHANGES_REQUESTED** [review]
Thanks @ManyRios, some of the details are incomplete on the exchanges 
Supports: Transparent / Shielded is a vital piece of information!

Feel free to join us in: https://discord.gg/zcash

**Review by ManyRios — COMMENTED** [review]
Update for Transparent/Shielded reviews

**Pull request merged**
